/*
ICTSURVEYUSER
*/
CREATE TABLE ICTUSER(
    USER_ID VARCHAR(200) PRIMARY KEY,
    USER_PW VARCHAR(255),
    USER_NAME VARCHAR(255),
    USER_EMAIL VARCHAR(255),
    COMP_ID VARCHAR(255),
    DEPT_NAME VARCHAR(255),
    USER_DIV VARCHAR(1),/*0 : MASTER, 1 : ADMIN, 2 : USER*/
    USER_SEX VARCHAR(1), /* 0 : MALE, 1 : FEMALE */
    INST_TIME VARCHAR(14),
    UPDT_TIME VARCHAR(14)
);
INSERT INTO ICTUSER(USER_ID, USER_PW, USER_NAME, USER_EMAIL, COMP_ID, DEPT_NAME, USER_DIV, USER_SEX, INST_TIME, UPDT_TIME)
VALUES('admin', 'admin##3804', '관리자', 'sehoakasayho@gmail.com', 'K001', 'IT', '0', '0', TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'), NULL);
INSERT INTO ICTUSER(USER_ID, USER_PW, USER_NAME, USER_EMAIL, COMP_ID, DEPT_NAME, USER_DIV, USER_SEX, INST_TIME, UPDT_TIME)
VALUES('test', 'test##3804', '테스트사용자', 'sehoakasayho@naver.com', 'K001', 'IT', '1', '0', TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'), NULL);

CREATE TABLE ICTCOMPANY(
    COMPANY_ID VARCHAR(10) PRIMARY KEY,
    COMPANY_NAME VARCHAR(255),
    COMPANY_NAME_1 VARCHAR(255),
    DTL_NOTE VARCHAR(255),
    INST_TIME VARCHAR(14),
    UPDT_TIME VARCHAR(14)
);
INSERT INTO ICTCOMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_NAME_1, DTL_NOTE, INST_TIME, UPDT_TIME)
VALUES('K001', 'KTR', '한국화학융합시험연구원', 'test data', TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'), NULL);
INSERT INTO ICTCOMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_NAME_1, DTL_NOTE, INST_TIME, UPDT_TIME)
VALUES('K002', 'KCL', '한국건설생활환경시험연구원', 'test Sㄱㄴㅇdata', TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'), NULL);


/* 설문 마스터 & 디테일 */
CREATE TABLE ICTSURVEYXM(
    SRVY_ID VARCHAR(10) PRIMARY KEY,
    SRVY_TITL VARCHAR(100),
    DTL_NOTE VARCHAR(255),
    INST_TIME VARCHAR(14),
    UPDT_TIME VARCHAR(14)
);

INSERT INTO ICTSURVEYXM
VALUES('2021060001', '테스트 설문1', '테스트설문입니다.1', TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'));
INSERT INTO ICTSURVEYXM
VALUES('2021060002', '테스트 설문2', '테스트설문입니다2.', TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'));

/* 디테일은 설문 내용 및 가중치를 보고 설계 완성시키기 */
CREATE TABLE ICTSURVEYXD(
    SRVY_ID VARCHAR(10) PRIMARY KEY,
    QSTN_SEQ NUMBER PRIMARY KEY,
    QSTN_TITL VARCHAR(255),
    QSTN_OPTN_1 VARCHAR(255)
);