/*
ICTSURVEYUSER
*/
CREATE TABLE ICTUSER(
    USER_ID VARCHAR(200) PRIMARY KEY,
    USER_PW VARCHAR(255),
    USER_NAME VARCHAR(255),
    USER_EMAIL VARCHAR(255),
    COMP_ID VARCHAR(255),
    DEPT_NAME VARCHAR(255),
    USER_DIV VARCHAR(1),/*0 : MASTER, 1 : ADMIN, 2 : USER*/
    INST_TIME VARCHAR(14),
    UPDT_TIME VARCHAR(14)
);
INSERT INTO ICTUSER(USER_ID, USER_PW, USER_NAME, USER_EMAIL, COMP_ID, DEPT_NAME, USER_DIV, INST_TIME, UPDT_TIME)
VALUES('admin', 'admin##3804', '관리자', 'sehoakasayho@gmail.com', 'K001', 'IT', '0', TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'), NULL);
INSERT INTO ICTUSER(USER_ID, USER_PW, USER_NAME, USER_EMAIL, COMP_ID, DEPT_NAME, USER_DIV, INST_TIME, UPDT_TIME)
VALUES('test', 'test##3804', '테스트사용자', 'sehoakasayho@naver.com', 'K001', 'IT', '1', TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'), NULL);

CREATE TABLE ICTCOMPANY(
    COMPANY_ID VARCHAR(10) PRIMARY KEY,
    COMPANY_NAME VARCHAR(255),
    COMPANY_NAME_1 VARCHAR(255),
    DTL_NOTE VARCHAR(255),
    INST_TIME VARCHAR(14),
    UPDT_TIME VARCHAR(14)
);
INSERT INTO ICTCOMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_NAME_1, DTL_NOTE, INST_TIME, UPDT_TIME)
VALUES('K001', 'KTR', '한국화학융합시험연구원', 'test data', TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'), NULL);
INSERT INTO ICTCOMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_NAME_1, DTL_NOTE, INST_TIME, UPDT_TIME)
VALUES('K002', 'KCL', '한국건설생활환경시험연구원', 'test Sㄱㄴㅇdata', TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'), NULL);
