/*
ICTSURVEYUSER
*/
CREATE TABLE ICTSURVEYUSER(
    USER_ID VARCHAR(200) PRIMARY KEY,
    USER_PW VARCHAR(255),
    USER_NAME VARCHAR(255),
    USER_EMAIL VARCHAR(255),
    COMP_NAME VARCHAR(255),
    DEPT_NAME VARCHAR(255),
    USER_DIV VARCHAR(1),/*0 : MASTER, 1 : ADMIN, 2 : USER*/
    INST_TIME VARCHAR(14),
    UPDT_TIME VARCHAR(14)
);