const pool = require("../db.js").pool;

//유저의 설문 진행여부 확인
exports.searchSurveyUser = async (parameters) => {
  const result = await pool.query(
    `SELECT A.USER_ID
    , B.USER_NAME
    , (SELECT COMPANY_NAME FROM ICTCOMPANY X WHERE X.COMPANY_ID = B.COMP_ID) AS COMPANY_NAME
    , B.DEPT_NAME
    , A.SRVY_ID
    , C.SRVY_TITL
    , C.DTL_NOTE
    , T.START_TIME
    , T.END_TIME
    , CASE WHEN SUM(CASE WHEN QSTN_ANS = '0' THEN 1 ELSE 0 END) > 0 THEN 'N'
             ELSE 'Y'
      END AS DONE_YN
FROM ICTSURVEYUSER T
LEFT OUTER JOIN ICTSURVEYANSWER A
ON T.USER_ID = A.USER_ID
AND T.SRVY_ID = A.SRVY_ID
LEFT OUTER JOIN ICTUSER B
ON A.USER_ID = B.USER_ID
LEFT OUTER JOIN ICTSURVEYXM C
ON A.SRVY_ID = C.SRVY_ID
GROUP BY A.USER_ID
, B.USER_NAME
, (SELECT COMPANY_NAME FROM ICTCOMPANY X WHERE X.COMPANY_ID = B.COMP_ID)
, B.DEPT_NAME
, A.SRVY_ID
, C.SRVY_TITL
, C.DTL_NOTE
, T.START_TIME
, T.END_TIME`,
    parameters
  );

  return result.rows;
};
